version: '3.4'
x-var:
  - &DATABASE_USERNAME testuser
  - &DATABASE_PASSWORD testuser
volumes:
  prototypen-db-vol:
services:
  database:
    extends:
      file: docker-compose-services.yaml
      service: database
  app:
    image: maven:3-jdk-11
    environment:
      DATABASE_SERVICE: db.prototypen:5432
      DATABASE_USER: *DATABASE_USERNAME
      DATABASE_PASSWORD: *DATABASE_PASSWORD
    hostname: prototypen
    container_name: prototypen
    working_dir: /app
    command: sh -c "mvn -U clean install -P compose && java -jar prototypen-boot/target/prototypen-boot.jar --spring.profiles.active=compose"
    volumes:
      - ./:/app/
    depends_on:
      - database
    ports:
      - "8080:8080"
