name: Magen Build, Generate Docker Image and Publish to AWS ECR
on:
  push:
    paths-ignore:
      - 'charts/**'
    branches: [ "develop" ]
env:
  AWS_REGION: "eu-west-3"
  REPO_NAME: ${{ github.event.repository.name }}
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout and committing infra updated version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::179934523585:role/ecr-publisher
        role-session-name: publish_ecr_session
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - uses: int128/create-ecr-repository-action@v1
      with:
        repository:  ${{ env.REPO_NAME }}
    - uses: actions/checkout@v3
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: version
    - name: Show extracted Maven project version
      run: echo ${{ steps.version.outputs.version }}
    - name: Maven Build
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - name: Build the Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "Building image..."
        docker build . --file Dockerfile --tag $ECR_REGISTRY/$REPO_NAME:${{ steps.version.outputs.version }}.alpha.${{github.run_id}}.${{github.run_attempt}}
        echo "Pushing image to ECR..."+$ECR_REGISTRY/$REPO_NAME:${{ steps.version.outputs.version }}.alpha.${{github.run_id}}.${{github.run_attempt}}
        docker push $ECR_REGISTRY/$REPO_NAME:${{ steps.version.outputs.version }}.alpha.${{github.run_id}}.${{github.run_attempt}}
    - name: Update Repository and Version
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          repo=$(cat ./charts/$REPO_NAME/values.yaml | grep repository: | awk '{print $2}')
          sed -i "s#$repo#$ECR_REGISTRY/$REPO_NAME#" ./charts/$REPO_NAME/values.yaml
          version=$(cat ./charts/$REPO_NAME/values.yaml | grep version: | awk '{print $2}')
          sed -i "s#$version#${{ steps.version.outputs.version }}.alpha.${{github.run_id}}.${{github.run_attempt}}#" ./charts/$REPO_NAME/values.yaml
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "Version updated"
